[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/denite_conf.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
